// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgOt-yv6YUmFU0eArS-8dBOfRHtf6D2xo',
    appId: '1:647266404306:web:d84e6ee291a6e8dbfaaa0b',
    messagingSenderId: '647266404306',
    projectId: 'chat-flutter-99c3d',
    authDomain: 'chat-flutter-99c3d.firebaseapp.com',
    databaseURL: 'https://chat-flutter-99c3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-flutter-99c3d.appspot.com',
    measurementId: 'G-M1S1KKC18E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIk8N3yw9HmXS-tmsuDTPnl_bZ9lxuehY',
    appId: '1:647266404306:android:74fea55517937607faaa0b',
    messagingSenderId: '647266404306',
    projectId: 'chat-flutter-99c3d',
    databaseURL: 'https://chat-flutter-99c3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-flutter-99c3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtx4gqGVaXsKRnjPOr_39nvaXNbBREzOE',
    appId: '1:647266404306:ios:6d4fee93bf0dc9acfaaa0b',
    messagingSenderId: '647266404306',
    projectId: 'chat-flutter-99c3d',
    databaseURL: 'https://chat-flutter-99c3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-flutter-99c3d.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );
}
